# Generated by Django 5.0.6 on 2026-04-18 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.IntegerField(default=10)),
                ('available_rooms', models.IntegerField(default=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('amenities', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='locations.city')),
            ],
            options={
                'ordering': ['price_per_night'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='hotels_hote_city_id_fb7985_idx'), models.Index(fields=['price_per_night'], name='hotels_hote_price_p_7002d9_idx')],
            },
        ),
    ]
